### ISSUE TITLE
Red Renderer (OpenVR DX11)

### ISSUE THREAD

**Issue by immersioTV** [tebjan/VVVV.OpenVR#1]
Hi Tebjan!

1 - I create a new empty VVVV patch
SteamVR is activated and Ready. 
HMD shows the "Steam/THIS IS REAL" scene in DirectMode.

2 - Create New Node / Renderer (OpenVR DX11). I link a Quad DX11 Layer in the Renderer.

3 - **Renderer module is red**. Inside the module, **Camera (OpenVR) is red**.
The HMD shows again the THIS IS REAL scene.
Compositor Output Pin Error: DoNotHaveFocus

4- Specs:
VVVV.OpenVR_AnyCPU_V2
VVVV 34.2 x64
dx11 (b33.7)
HTC Vive / Direct Mode / SteamVR
Connected to one 1024*768 screen in DVI @75fps refresh rate
NVidia 980Ti
Windows 8.1
i7-4790K 4.00Ghz
RAM 16Go
64bits

What are your dx11 version and VVVV version when you use OpenVR?

5 - Console TTY says : 

```

VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)
00:16:30 ERR : Exception occured in TMPluginWrapperNode.Evaluate
00:16:30 ERR : Object reference not set to an instance of an object.
00:16:30 ERR : Exception occured in TMPluginWrapperNode.Evaluate
00:16:30 ERR : Access violation at address 00007FFCA21782C0. Write of address 00007FFCA21782C0
00:16:30 ERR : Exception caused by node during render :/75/2/15
00:16:30 ERR : System.DivideByZeroException in VVVV.PluginInterfaces: Attempted to divide by zero.


Stacktrace:
   at VVVV.PluginInterfaces.V2.Spread`1.get_Item(Int32 index)
   at VVVV.DX11.Lib.Rendering.RenderTargetManager.GetRenderTarget(DX11RenderContext context)
   at VVVV.DX11.DX11TempRTRendererNode.OnUpdate(DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Update(IPluginIO pin, DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Render(DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)

00:16:30  -  : Stack Trace
00:16:30  -  :    at VVVV.PluginInterfaces.V2.Spread`1.get_Item(Int32 index)
   at VVVV.DX11.Lib.Rendering.RenderTargetManager.GetRenderTarget(DX11RenderContext context)
   at VVVV.DX11.DX11TempRTRendererNode.OnUpdate(DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Update(IPluginIO pin, DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Render(DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)
00:16:30 ERR : Exception caused by node during update :/75/2/16
00:16:30 ERR : System.DivideByZeroException in VVVV.PluginInterfaces: Attempted to divide by zero.

Stacktrace:
   at VVVV.PluginInterfaces.V2.Spread`1.get_Item(Int32 index)
   at VVVV.DX11.Lib.Rendering.RenderTargetManager.GetRenderTarget(DX11RenderContext context)
   at VVVV.DX11.DX11TempRTRendererNode.OnUpdate(DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Update(IPluginIO pin, DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)

00:16:30  -  : Stack Trace
00:16:30  -  :    at VVVV.PluginInterfaces.V2.Spread`1.get_Item(Int32 index)
   at VVVV.DX11.Lib.Rendering.RenderTargetManager.GetRenderTarget(DX11RenderContext context)
   at VVVV.DX11.DX11TempRTRendererNode.OnUpdate(DX11RenderContext context)
   at VVVV.DX11.AbstractDX11Renderer2DNode.Update(IPluginIO pin, DX11RenderContext context)
   at VVVV.DX11.Lib.RenderGraph.DX11DeviceRenderer.ProcessNode(DX11Node node)
00:16:30 ERR : Exception occured in TMPluginWrapperNode.Evaluate
00:16:30 ERR : Object reference not set to an instance of an object.
```

6 - When I open the 01_OpenVRDemo.v4p, the Renderer (OpenVR DX11) is not red, the patch is working.

**Comment by tebjan** [comment]
it seems that the patch with the renderer is somewhere deeper in the patch structure, or one of the renderers is not in foreground... do you do any multi pass rendering?

**Comment by tebjan** [comment]
ah.. and does it work as soon as you create a Poser node?

**Comment by immersioTV** [comment]
Hi Tebjan, 

No more Red nodes with the new version (OpenVR v3). 

Thank you !
